import {
    faCheck,
    faFolder,
    faLanguage,
    faCubes,
    faCube,
    faFolderPlus,
    faPlusSquare,
    faBars,
    faPlus,
    faList,
    faDesktop,
    faSave,
    faFileExport,
    faExternalLinkAlt,
    faPhotoVideo,
    faSitemap, faFile,
    faImage, faHashtag, faTimes,
    faSortUp, faSortDown
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = [
    faCheck,
    faLanguage,
    faFolder,
    faCubes,
    faCube,
    faFolderPlus,
    faPlusSquare,
    faBars,
    faPlus,
    faList,
    faDesktop,
    faSave,
    faFileExport,
    faExternalLinkAlt,
    faPhotoVideo,
    faFolder, faSitemap, faFile, faPlus,
    faImage, faHashtag, faTimes,
    faSortUp, faSortDown
]
