export const PROPERTY_METADATA_KEY = Symbol('PROPERTY_METADATA_KEY');
export const PROPERTIES_METADATA_KEY = Symbol('PROPERTIES_METADATA_KEY');

export const VALIDATION_METADATA_KEY = Symbol('VALIDATION_METADATA_KEY');

export const PAGE_TYPE_METADATA_KEY = Symbol('PAGE_TYPE_METADATA_KEY');
export const PAGE_TYPE_INDICATOR = Symbol('PAGE_TYPE_INDICATOR');

export const BLOCK_TYPE_METADATA_KEY = Symbol('BLOCK_TYPE_METADATA_KEY');
export const BLOCK_TYPE_INDICATOR = Symbol('BLOCK_TYPE_INDICATOR');

export const MEDIA_TYPE_METADATA_KEY = Symbol('MEDIA_TYPE_METADATA_KEY');
export const MEDIA_TYPE_INDICATOR = Symbol('MEDIA_TYPE_INDICATOR');

